exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title:  Advocate Anand Bali and Associates. A Delhi based Law Firm 
descriptions: Anand Bali and Associates, is a Delhi based Law Firm
subtitle: Anand Bali and Associates, is a Delhi based Law Firm
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: http://www.advocateanandbaliandassociates.com # the base hostname & protocol for your site
baseurl: ""
cover: "/img/cover.png"
logo: "/img/logo.png"
author: "anandbali"
# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-91325307-1"
  